<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="kentico.xperience.admin" Version="31.8.2" />
    <PackageReference Include="kentico.xperience.azurestorage" Version="31.8.2" />
    <PackageReference Include="kentico.xperience.imageprocessing" Version="31.8.2" />
    <PackageReference Include="kentico.xperience.webapp" Version="31.8.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Kickstart.Entities\Kickstart.Entities.csproj" />
  </ItemGroup>
</Project>